name: mailtm_client
description: This package is a simple but complete mail.tm api wrapper, you can use this to save and manage your accounts, as well read all your temporary emails.
version: 1.0.6
homepage: https://github.com/GiuseppeFn/mailtm_client
repository: https://github.com/GiuseppeFn/mailtm_client

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.4
  username_gen: ^1.0.4
  path: ^1.8.1

dev_dependencies: 
  lints: ^1.0.1
